import { FileText, Globe, Newspaper, Share2, Mail } from "lucide-react";
import { desc } from "drizzle-orm";
import {
  db,
  geoContentDrafts,
  blogPostDrafts,
  socialPostDrafts,
  emailCampaignDrafts,
} from "@/db";
import { AdminShell } from "@/components/admin/admin-shell";
import { PlaceholderPanel } from "@/components/admin/placeholder-panel";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { contentStatusMeta, formatDate } from "@/lib/admin-format";
import type { ContentStatus } from "@/db/schema";

// Reads live data — never prerender at build time.
export const dynamic = "force-dynamic";

function StatusBadge({ status }: { status: ContentStatus }) {
  const meta = contentStatusMeta[status];
  return <Badge variant={meta.variant}>{meta.label}</Badge>;
}

type Row = {
  key: string;
  title: string;
  meta: string;
  preview: string;
  status: ContentStatus;
  date: Date | string | null;
};

function DraftGroup({
  icon: Icon,
  title,
  description,
  rows,
}: {
  icon: React.ComponentType<{ className?: string }>;
  title: string;
  description: string;
  rows: Row[];
}) {
  return (
    <section className="flex flex-col gap-3">
      <div className="flex items-center gap-2">
        <div className="flex size-8 items-center justify-center rounded-lg bg-primary/10 text-primary">
          <Icon className="size-4" />
        </div>
        <div>
          <h2 className="font-heading text-sm font-semibold">{title}</h2>
          <p className="text-xs text-muted-foreground">{description}</p>
        </div>
        <span className="ml-auto text-xs text-muted-foreground">{rows.length}</span>
      </div>

      {rows.length === 0 ? (
        <Card className="px-4 py-6 text-center text-sm text-muted-foreground">No drafts yet.</Card>
      ) : (
        <Card className="divide-y p-0">
          {rows.map((row) => (
            <div key={row.key} className="flex items-start gap-4 px-4 py-3">
              <div className="min-w-0 flex-1">
                <div className="flex items-center gap-2">
                  <p className="truncate font-medium">{row.title}</p>
                  <StatusBadge status={row.status} />
                </div>
                <p className="text-xs text-muted-foreground">{row.meta}</p>
                <p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{row.preview}</p>
              </div>
              <span className="shrink-0 text-xs whitespace-nowrap text-muted-foreground">
                {formatDate(row.date)}
              </span>
            </div>
          ))}
        </Card>
      )}
    </section>
  );
}

export default async function AdminContentPage() {
  const [geo, blog, social, email] = await Promise.all([
    db.select().from(geoContentDrafts).orderBy(desc(geoContentDrafts.updatedAt)),
    db.select().from(blogPostDrafts).orderBy(desc(blogPostDrafts.updatedAt)),
    db.select().from(socialPostDrafts).orderBy(desc(socialPostDrafts.updatedAt)),
    db.select().from(emailCampaignDrafts).orderBy(desc(emailCampaignDrafts.updatedAt)),
  ]);

  const total = geo.length + blog.length + social.length + email.length;

  if (total === 0) {
    return (
      <AdminShell title="Content">
        <PlaceholderPanel
          icon={FileText}
          title="No drafts yet"
          description="Marketing/GEO content generated by the workspaces will show up here for review before it's published to the site."
        />
      </AdminShell>
    );
  }

  const geoRows: Row[] = geo.map((d) => ({
    key: d.id,
    title: d.slug,
    meta: `${d.targetPage}${d.targetQuery ? ` · "${d.targetQuery}"` : ""}`,
    preview: d.en.intro,
    status: d.status,
    date: d.dateModified ?? d.updatedAt,
  }));

  const blogRows: Row[] = blog.map((d) => ({
    key: d.id,
    title: d.title.en,
    meta: d.tags.length > 0 ? d.tags.join(", ") : d.slug,
    preview: d.excerpt.en,
    status: d.status,
    date: d.dateModified ?? d.updatedAt,
  }));

  const socialRows: Row[] = social.map((d) => ({
    key: d.id,
    title: d.platform.charAt(0).toUpperCase() + d.platform.slice(1),
    meta: d.hashtags.map((h) => `#${h}`).join(" "),
    preview: d.caption.en,
    status: d.status,
    date: d.scheduledFor ?? d.updatedAt,
  }));

  const emailRows: Row[] = email.map((d) => ({
    key: d.id,
    title: d.subject.en,
    meta: `Segment: ${d.segment}`,
    preview: d.preheader.en,
    status: d.status,
    date: d.scheduledFor ?? d.updatedAt,
  }));

  return (
    <AdminShell title="Content">
      <div className="flex flex-col gap-8">
        <DraftGroup
          icon={Globe}
          title="GEO content blocks"
          description="Answer-first blocks from the geo-content pipeline."
          rows={geoRows}
        />
        <DraftGroup
          icon={Newspaper}
          title="Blog posts"
          description="Long-form articles awaiting review."
          rows={blogRows}
        />
        <DraftGroup
          icon={Share2}
          title="Social posts"
          description="Scheduled and drafted social content."
          rows={socialRows}
        />
        <DraftGroup
          icon={Mail}
          title="Email campaigns"
          description="Newsletter and lifecycle emails."
          rows={emailRows}
        />
      </div>
    </AdminShell>
  );
}
