import { FileText } from "lucide-react";
import { AdminShell } from "@/components/admin/admin-shell";
import { PlaceholderPanel } from "@/components/admin/placeholder-panel";

export default function AdminContentPage() {
  return (
    <AdminShell title="Content">
      <PlaceholderPanel
        icon={FileText}
        title="No drafts yet"
        description="Marketing/GEO content generated by the workspaces will show up here for review before it's published to the site."
      />
    </AdminShell>
  );
}
