import { FileText, Globe, Newspaper, Share2, Mail } from "lucide-react";
import { count, desc } from "drizzle-orm";
import {
  db,
  geoContentDrafts,
  blogPostDrafts,
  socialPostDrafts,
  emailCampaignDrafts,
} from "@/db";
import { requireAdmin } from "@/lib/admin-auth";
import { AdminShell } from "@/components/admin/admin-shell";
import { AdminPagination } from "@/components/admin/pagination";
import { PlaceholderPanel } from "@/components/admin/placeholder-panel";
import { lastPage, pageSlice, readPageParam } from "@/lib/admin-pagination";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { contentStatusMeta, formatDate } from "@/lib/admin-format";
import type { ContentStatus } from "@/db/schema";

// Reads live data — never prerender at build time.
export const dynamic = "force-dynamic";

function StatusBadge({ status }: { status: ContentStatus }) {
  const meta = contentStatusMeta[status];
  return <Badge variant={meta.variant}>{meta.label}</Badge>;
}

type Row = {
  key: string;
  title: string;
  meta: string;
  preview: string;
  status: ContentStatus;
  date: Date | string | null;
};

function DraftGroup({
  icon: Icon,
  title,
  description,
  rows,
  total,
  page,
  hrefFor,
}: {
  icon: React.ComponentType<{ className?: string }>;
  title: string;
  description: string;
  rows: Row[];
  total: number;
  page: number;
  hrefFor: (page: number) => string;
}) {
  return (
    <section className="flex flex-col gap-3">
      <div className="flex items-center gap-2">
        <div className="flex size-8 items-center justify-center rounded-lg bg-primary/10 text-primary">
          <Icon className="size-4" />
        </div>
        <div>
          <h2 className="font-heading text-sm font-semibold">{title}</h2>
          <p className="text-xs text-muted-foreground">{description}</p>
        </div>
        <span className="ml-auto text-xs text-muted-foreground">{total}</span>
      </div>

      {rows.length === 0 ? (
        <Card className="px-4 py-6 text-center text-sm text-muted-foreground">No drafts yet.</Card>
      ) : (
        <Card className="divide-y p-0">
          {rows.map((row) => (
            <div key={row.key} className="flex items-start gap-4 px-4 py-3">
              <div className="min-w-0 flex-1">
                <div className="flex items-center gap-2">
                  <p className="truncate font-medium">{row.title}</p>
                  <StatusBadge status={row.status} />
                </div>
                <p className="text-xs text-muted-foreground">{row.meta}</p>
                <p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{row.preview}</p>
              </div>
              <span className="shrink-0 text-xs whitespace-nowrap text-muted-foreground">
                {formatDate(row.date)}
              </span>
            </div>
          ))}
        </Card>
      )}

      <AdminPagination page={page} total={total} label={`${title} pages`} hrefFor={hrefFor} />
    </section>
  );
}

/** The four draft pipelines, each paginated independently by its own query param. */
const GROUPS = ["geo", "blog", "social", "email"] as const;
type GroupKey = (typeof GROUPS)[number];

export default async function AdminContentPage({
  searchParams,
}: {
  searchParams: Promise<Partial<Record<GroupKey, string>>>;
}) {
  await requireAdmin();

  const params = await searchParams;

  // Counts first, so each group's page can be clamped to what actually exists.
  const [[geoTotal], [blogTotal], [socialTotal], [emailTotal]] = await db.batch([
    db.select({ n: count() }).from(geoContentDrafts),
    db.select({ n: count() }).from(blogPostDrafts),
    db.select({ n: count() }).from(socialPostDrafts),
    db.select({ n: count() }).from(emailCampaignDrafts),
  ]);

  const totals: Record<GroupKey, number> = {
    geo: geoTotal?.n ?? 0,
    blog: blogTotal?.n ?? 0,
    social: socialTotal?.n ?? 0,
    email: emailTotal?.n ?? 0,
  };
  const total = GROUPS.reduce((sum, key) => sum + totals[key], 0);

  if (total === 0) {
    return (
      <AdminShell>
        <PlaceholderPanel
          icon={FileText}
          title="No drafts yet"
          description="Marketing/GEO content generated by the workspaces will show up here for review before it's published to the site."
        />
      </AdminShell>
    );
  }

  // Requested page per group, never past that group's last page.
  const pages = Object.fromEntries(
    GROUPS.map((key) => [
      key,
      Math.min(readPageParam(params[key]), lastPage(totals[key])),
    ]),
  ) as Record<GroupKey, number>;

  /** A link that moves one group to `page` and leaves the other three alone. */
  function hrefFor(group: GroupKey, page: number): string {
    const query = new URLSearchParams();
    for (const key of GROUPS) {
      const value = key === group ? page : pages[key];
      if (value > 1) query.set(key, String(value));
    }
    const search = query.toString();
    return search ? `/admin/content?${search}` : "/admin/content";
  }

  const slices = Object.fromEntries(GROUPS.map((key) => [key, pageSlice(pages[key])])) as Record<
    GroupKey,
    { limit: number; offset: number }
  >;

  const [geo, blog, social, email] = await db.batch([
    db
      .select()
      .from(geoContentDrafts)
      .orderBy(desc(geoContentDrafts.updatedAt))
      .limit(slices.geo.limit)
      .offset(slices.geo.offset),
    db
      .select()
      .from(blogPostDrafts)
      .orderBy(desc(blogPostDrafts.updatedAt))
      .limit(slices.blog.limit)
      .offset(slices.blog.offset),
    db
      .select()
      .from(socialPostDrafts)
      .orderBy(desc(socialPostDrafts.updatedAt))
      .limit(slices.social.limit)
      .offset(slices.social.offset),
    db
      .select()
      .from(emailCampaignDrafts)
      .orderBy(desc(emailCampaignDrafts.updatedAt))
      .limit(slices.email.limit)
      .offset(slices.email.offset),
  ]);

  const geoRows: Row[] = geo.map((d) => ({
    key: d.id,
    title: d.slug,
    meta: `${d.targetPage}${d.targetQuery ? ` · "${d.targetQuery}"` : ""}`,
    preview: d.en.intro,
    status: d.status,
    date: d.dateModified ?? d.updatedAt,
  }));

  const blogRows: Row[] = blog.map((d) => ({
    key: d.id,
    title: d.title.en,
    meta: d.tags.length > 0 ? d.tags.join(", ") : d.slug,
    preview: d.excerpt.en,
    status: d.status,
    date: d.dateModified ?? d.updatedAt,
  }));

  const socialRows: Row[] = social.map((d) => ({
    key: d.id,
    title: d.platform.charAt(0).toUpperCase() + d.platform.slice(1),
    meta: d.hashtags.map((h) => `#${h}`).join(" "),
    preview: d.caption.en,
    status: d.status,
    date: d.scheduledFor ?? d.updatedAt,
  }));

  const emailRows: Row[] = email.map((d) => ({
    key: d.id,
    title: d.subject.en,
    meta: `Segment: ${d.segment}`,
    preview: d.preheader.en,
    status: d.status,
    date: d.scheduledFor ?? d.updatedAt,
  }));

  return (
    <AdminShell>
      <div className="flex flex-col gap-8">
        <DraftGroup
          icon={Globe}
          title="GEO content blocks"
          description="Answer-first blocks from the geo-content pipeline."
          rows={geoRows}
          total={totals.geo}
          page={pages.geo}
          hrefFor={(n) => hrefFor("geo", n)}
        />
        <DraftGroup
          icon={Newspaper}
          title="Blog posts"
          description="Long-form articles awaiting review."
          rows={blogRows}
          total={totals.blog}
          page={pages.blog}
          hrefFor={(n) => hrefFor("blog", n)}
        />
        <DraftGroup
          icon={Share2}
          title="Social posts"
          description="Scheduled and drafted social content."
          rows={socialRows}
          total={totals.social}
          page={pages.social}
          hrefFor={(n) => hrefFor("social", n)}
        />
        <DraftGroup
          icon={Mail}
          title="Email campaigns"
          description="Newsletter and lifecycle emails."
          rows={emailRows}
          total={totals.email}
          page={pages.email}
          hrefFor={(n) => hrefFor("email", n)}
        />
      </div>
    </AdminShell>
  );
}
