/**
 * Emit the SQL that seeds the `experiences` table from the shipped catalogue in
 * `src/content/experiences.ts`.
 *
 *   cd web
 *   pnpm db:seed-experiences-sql > drizzle/0008_seed_experience_catalogue.sql
 *
 * Written rather than hand-typed because the seed is ~250 lines of bilingual
 * copy: transcribing it by hand is how a migration ends up shipping a different
 * catalogue from the one the fallback renders. Re-run it if the shipped
 * catalogue changes before the table is seeded in a given environment.
 *
 * The output is idempotent (`ON CONFLICT (slug) DO NOTHING`), so applying it to
 * a database whose operators have already edited the catalogue changes nothing.
 */
import { experiences } from "@/content/experiences";

/** Single-quote a string for SQL, doubling embedded quotes. */
function quote(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

/** A JSON value as a `jsonb` literal. */
function jsonb(value: unknown): string {
  return `${quote(JSON.stringify(value))}::jsonb`;
}

const header = `-- Seed: the experience catalogue.
--
-- Moves the offer (Rural Saloia and its add-ons) out of the TypeScript array in
-- src/content/experiences.ts and into the table Diogo & Rita edit at
-- /admin/experiences. The array stays as the fallback the site renders when this
-- table cannot be read — see src/lib/experience-catalogue.ts.
--
-- Generated by scripts/generate-experience-seed.ts. Idempotent: a slug that is
-- already present is left exactly as the operators have it.
`;

const rows = experiences.map((experience, index) => {
  const values = [
    quote(experience.slug),
    quote(experience.kind),
    quote(experience.icon),
    jsonb(experience.title),
    jsonb(experience.tagline),
    jsonb(experience.summary),
    jsonb(experience.description),
    jsonb(experience.duration),
    jsonb(experience.highlights),
    jsonb(experience.faqs),
    quote(experience.image),
    jsonb(experience.imageAlt),
    experience.pricing ? jsonb(experience.pricing) : "NULL",
    String(index),
  ];
  return `(\n  ${values.join(",\n  ")}\n)`;
});

process.stdout.write(
  `${header}
INSERT INTO "experiences" (
  "slug", "kind", "icon",
  "title", "tagline", "summary", "description", "duration", "highlights", "faqs",
  "image", "image_alt", "pricing", "sort_order"
) VALUES
${rows.join(",\n")}
ON CONFLICT ("slug") DO NOTHING;
`,
);
